/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.*;
import java.awt.event.*;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author IsilenceT
 */
public class AdminGUI extends javax.swing.JFrame {

    /**
     * Creates new form adminJFrame
     */
    
    
    private SimpleDateFormat dateFormat;
    private Calendar currentCal;
    private String currentdate, toDate;
    private JFileChooser file;
    
    
    public AdminGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        //test image url
//        try {
//            URL urltest = new URL("https://i.pinimg.com/originals/43/97/bd/4397bdfea4297f8c517f5901c72c31c3.png");
//            Image imagetest = ImageIO.read(urltest);
//            ImageIcon icon_search = new ImageIcon(new ImageIcon(imagetest).getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH));
//            lb_search_icon.setIcon(icon_search);
//        } catch (Exception ex){}
        
        ImageIcon icon_search = new ImageIcon(new ImageIcon(getClass().getResource("../image/icon_search.png")).getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH));
        lb_menu_search.setIcon(icon_search);

        ImageIcon icon_borrowNreturn = new ImageIcon(new ImageIcon(getClass().getResource("../image/icon_borrow.png")).getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH));
        lb_menu_borrowNreturn.setIcon(icon_borrowNreturn);

        ImageIcon icon_borrowhistory = new ImageIcon(new ImageIcon(getClass().getResource("../image/icon_borrowhistory.png")).getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH));
        lb_menu_history.setIcon(icon_borrowhistory);

        ImageIcon icon_book = new ImageIcon(new ImageIcon(getClass().getResource("../image/icon_book.png")).getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH));
        lb_menu_book.setIcon(icon_book);
        
        ImageIcon icon_logout = new ImageIcon(new ImageIcon(getClass().getResource("../image/icon_logout.png")).getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH));
        lb_menu_logout.setIcon(icon_logout);
        
        
        ImageIcon icon_search_small = new ImageIcon(new ImageIcon(getClass().getResource("../image/icon_search.png")).getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH));
        btn_search.setIcon(icon_search_small);
        
        ImageIcon icon_clear_search = new ImageIcon(new ImageIcon(getClass().getResource("../image/icon_clear_search.png")).getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH));
        btn_reset.setIcon(icon_clear_search);
        
        ImageIcon img_book_sample = new ImageIcon(new ImageIcon(getClass().getResource("../image/book_sample.jpg")).getImage().getScaledInstance(300, 400, Image.SCALE_SMOOTH));
        lb_img_book1.setIcon(img_book_sample);
        lb_img_book2.setIcon(img_book_sample);
        
        //date for panel 
        dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        currentCal = Calendar.getInstance();
        currentdate = dateFormat.format(currentCal.getTime());
        tf_borrowdate1.setText(currentdate);
        
        //Filechooser for panel addbook
        file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home") + "/Desktop"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter(".jpg, .gif, .png", "jpg", "gif", "png");
//      file.addChoosableFileFilter(filter);
        file.setFileFilter(filter);
        
    }
    
    public void pa_center_changeto(String panel_name){
        CardLayout cl = (CardLayout)(pa_center.getLayout());
        cl.show(pa_center, panel_name);
        System.out.println("change to " + panel_name);
    }
    
    public void lb_menu_mouseentered(MouseEvent evt){
        ((JLabel) evt.getSource()).setForeground(Color.red);
    }
    
    public void lb_menu_mouseexited(MouseEvent evt){
        ((JLabel) evt.getSource()).setForeground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pa_menu = new javax.swing.JPanel();
        lb_ADMIN = new javax.swing.JLabel();
        lb_menu_search = new javax.swing.JLabel();
        lb_menu_borrowNreturn = new javax.swing.JLabel();
        lb_menu_history = new javax.swing.JLabel();
        lb_menu_book = new javax.swing.JLabel();
        lb_menu_logout = new javax.swing.JLabel();
        pa_center = new javax.swing.JPanel();
        pa_search = new javax.swing.JPanel();
        lb_searchby = new javax.swing.JLabel();
        lb_searchdata = new javax.swing.JLabel();
        cbb_searchby = new javax.swing.JComboBox<>();
        tf_searchdata = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable_bookinfo = new javax.swing.JTable();
        pa_borrowNreturn = new javax.swing.JPanel();
        lb_tab_borrow = new javax.swing.JLabel();
        lb_tab_return = new javax.swing.JLabel();
        pa_borrowNreturn_cards = new javax.swing.JPanel();
        pa_borrow = new javax.swing.JPanel();
        lb_borrownumber1 = new javax.swing.JLabel();
        tf_borrownumber1 = new javax.swing.JTextField();
        lb_callnumber1 = new javax.swing.JLabel();
        tf_callnumber1 = new javax.swing.JTextField();
        lb_bookname1 = new javax.swing.JLabel();
        tf_bookname1 = new javax.swing.JTextField();
        lb_userid1 = new javax.swing.JLabel();
        tf_userid1 = new javax.swing.JTextField();
        lb_username1 = new javax.swing.JLabel();
        tf_username1 = new javax.swing.JTextField();
        cbb_borrowdays1 = new javax.swing.JComboBox<>();
        lb_borrowdays1 = new javax.swing.JLabel();
        tf_borrowdate1 = new javax.swing.JTextField();
        lb_borrowdate1 = new javax.swing.JLabel();
        lb_returndate1 = new javax.swing.JLabel();
        tf_returndate1 = new javax.swing.JTextField();
        lb_img_book1 = new javax.swing.JLabel();
        btn_record_borrowing = new javax.swing.JButton();
        pa_return = new javax.swing.JPanel();
        lb_borrownumber2 = new javax.swing.JLabel();
        tf_borrownumber2 = new javax.swing.JTextField();
        lb_callnumber2 = new javax.swing.JLabel();
        tf_callnumber2 = new javax.swing.JTextField();
        lb_bookname2 = new javax.swing.JLabel();
        tf_bookname2 = new javax.swing.JTextField();
        lb_userid2 = new javax.swing.JLabel();
        tf_userid2 = new javax.swing.JTextField();
        lb_username2 = new javax.swing.JLabel();
        tf_username2 = new javax.swing.JTextField();
        tf_borrowdate2 = new javax.swing.JTextField();
        lb_borrowdate2 = new javax.swing.JLabel();
        lb_returndate2 = new javax.swing.JLabel();
        tf_returndate2 = new javax.swing.JTextField();
        lb_img_book2 = new javax.swing.JLabel();
        btn_record_returning = new javax.swing.JButton();
        pa_history = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTable_borrowhistory = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pa_book = new javax.swing.JPanel();
        lb_tab_addbook = new javax.swing.JLabel();
        lb_tab_removebook = new javax.swing.JLabel();
        pa_book_cards = new javax.swing.JPanel();
        pa_addbook = new javax.swing.JPanel();
        lb_callnumber3 = new javax.swing.JLabel();
        tf_callnumber3 = new javax.swing.JTextField();
        lb_bookname3 = new javax.swing.JLabel();
        tf_bookname3 = new javax.swing.JTextField();
        lb_img_book3 = new javax.swing.JLabel();
        btn_addbook = new javax.swing.JButton();
        lb_bookname5 = new javax.swing.JLabel();
        btn_choosefile = new javax.swing.JButton();
        lb_filename = new javax.swing.JLabel();
        pa_removebook = new javax.swing.JPanel();
        lb_callnumber4 = new javax.swing.JLabel();
        tf_callnumber4 = new javax.swing.JTextField();
        lb_bookname4 = new javax.swing.JLabel();
        tf_bookname4 = new javax.swing.JTextField();
        lb_img_book4 = new javax.swing.JLabel();
        btn_removebook = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library System");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        pa_menu.setBackground(new java.awt.Color(204, 255, 204));
        pa_menu.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 1, Color.black));
        pa_menu.setMinimumSize(new java.awt.Dimension(200, 500));
        pa_menu.setPreferredSize(new java.awt.Dimension(200, 500));

        lb_ADMIN.setBackground(new java.awt.Color(153, 255, 204));
        lb_ADMIN.setFont(new java.awt.Font("Kanit", 1, 36)); // NOI18N
        lb_ADMIN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_ADMIN.setText("ADMIN");
        lb_ADMIN.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.black));
        lb_ADMIN.setOpaque(true);

        lb_menu_search.setFont(new java.awt.Font("Kanit", 0, 24)); // NOI18N
        lb_menu_search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_menu_search.setText("ค้นหาหนังสือ");
        lb_menu_search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_menu_search.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_menu_search.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lb_menu_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_menu_searchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_menu_searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_menu_searchMouseExited(evt);
            }
        });

        lb_menu_borrowNreturn.setFont(new java.awt.Font("Kanit", 0, 24)); // NOI18N
        lb_menu_borrowNreturn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_menu_borrowNreturn.setText("<html><body style=\"text-align: center\">ทำรายการ<br>ยืม-คืนหนังสือ</body></html>");
        lb_menu_borrowNreturn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_menu_borrowNreturn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_menu_borrowNreturn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lb_menu_borrowNreturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_menu_borrowNreturnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_menu_borrowNreturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_menu_borrowNreturnMouseExited(evt);
            }
        });

        lb_menu_history.setFont(new java.awt.Font("Kanit", 0, 24)); // NOI18N
        lb_menu_history.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_menu_history.setText("<html><body style=\"text-align: center\">ประวัติการ<br>ยืม-คืนหนังสือ</body></html>");
        lb_menu_history.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_menu_history.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_menu_history.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lb_menu_history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_menu_historyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_menu_historyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_menu_historyMouseExited(evt);
            }
        });

        lb_menu_book.setFont(new java.awt.Font("Kanit", 0, 24)); // NOI18N
        lb_menu_book.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_menu_book.setText("ทะเบียนหนังสือ");
        lb_menu_book.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_menu_book.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_menu_book.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lb_menu_book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_menu_bookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_menu_bookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_menu_bookMouseExited(evt);
            }
        });

        lb_menu_logout.setFont(new java.awt.Font("Kanit", 0, 24)); // NOI18N
        lb_menu_logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_menu_logout.setText("Logout");
        lb_menu_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_menu_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_menu_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_menu_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_menu_logoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pa_menuLayout = new javax.swing.GroupLayout(pa_menu);
        pa_menu.setLayout(pa_menuLayout);
        pa_menuLayout.setHorizontalGroup(
            pa_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_ADMIN, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(lb_menu_borrowNreturn)
            .addComponent(lb_menu_search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_menu_book, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_menu_history, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(lb_menu_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pa_menuLayout.setVerticalGroup(
            pa_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa_menuLayout.createSequentialGroup()
                .addComponent(lb_ADMIN, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_menu_search, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_menu_borrowNreturn, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_menu_history, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_menu_book, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addGap(57, 57, 57)
                .addComponent(lb_menu_logout)
                .addContainerGap())
        );

        getContentPane().add(pa_menu, java.awt.BorderLayout.LINE_START);

        pa_center.setBackground(new java.awt.Color(255, 255, 255));
        pa_center.setLayout(new java.awt.CardLayout());

        pa_search.setBackground(new java.awt.Color(204, 204, 255));

        lb_searchby.setFont(new java.awt.Font("Kanit", 0, 18)); // NOI18N
        lb_searchby.setText("ค้นหาจาก");

        lb_searchdata.setFont(new java.awt.Font("Kanit", 0, 18)); // NOI18N
        lb_searchdata.setText("ข้อมูลที่ต้องการค้นหา");

        cbb_searchby.setFont(new java.awt.Font("Kanit", 0, 18)); // NOI18N
        cbb_searchby.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "เลขเรียกหนังสือ", "ชื่อหนังสือ", "ชิ่อผู้แต่ง" }));

        tf_searchdata.setFont(new java.awt.Font("Kanit", 0, 18)); // NOI18N

        btn_search.setFont(new java.awt.Font("Kanit", 0, 24)); // NOI18N
        btn_search.setText("ค้นหา");
        btn_search.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_search.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_search.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        btn_reset.setFont(new java.awt.Font("Kanit", 0, 24)); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_reset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        JTable_bookinfo.setAutoCreateRowSorter(true);
        JTable_bookinfo.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        JTable_bookinfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "เลขเรียกหนังสือ", "ชื่อหนังสือ", "ชื่อผู้แต่ง", "สถานะ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTable_bookinfo);
        if (JTable_bookinfo.getColumnModel().getColumnCount() > 0) {
            JTable_bookinfo.getColumnModel().getColumn(0).setMinWidth(150);
            JTable_bookinfo.getColumnModel().getColumn(0).setPreferredWidth(150);
            JTable_bookinfo.getColumnModel().getColumn(0).setMaxWidth(150);
            JTable_bookinfo.getColumnModel().getColumn(0).setHeaderValue("เลขเรียกหนังสือ");
            JTable_bookinfo.getColumnModel().getColumn(1).setMinWidth(300);
            JTable_bookinfo.getColumnModel().getColumn(1).setPreferredWidth(300);
            JTable_bookinfo.getColumnModel().getColumn(1).setMaxWidth(300);
            JTable_bookinfo.getColumnModel().getColumn(1).setHeaderValue("ชื่อหนังสือ");
            JTable_bookinfo.getColumnModel().getColumn(2).setMinWidth(200);
            JTable_bookinfo.getColumnModel().getColumn(2).setPreferredWidth(200);
            JTable_bookinfo.getColumnModel().getColumn(2).setMaxWidth(300);
            JTable_bookinfo.getColumnModel().getColumn(2).setHeaderValue("ชื่อผู้แต่ง");
            JTable_bookinfo.getColumnModel().getColumn(3).setMinWidth(200);
            JTable_bookinfo.getColumnModel().getColumn(3).setPreferredWidth(200);
            JTable_bookinfo.getColumnModel().getColumn(3).setMaxWidth(200);
            JTable_bookinfo.getColumnModel().getColumn(3).setHeaderValue("สถานะ");
        }

        javax.swing.GroupLayout pa_searchLayout = new javax.swing.GroupLayout(pa_search);
        pa_search.setLayout(pa_searchLayout);
        pa_searchLayout.setHorizontalGroup(
            pa_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa_searchLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(pa_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pa_searchLayout.createSequentialGroup()
                        .addGroup(pa_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb_searchdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_searchby, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pa_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_searchdata, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbb_searchby, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        pa_searchLayout.setVerticalGroup(
            pa_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa_searchLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(pa_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pa_searchLayout.createSequentialGroup()
                        .addGroup(pa_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_searchby)
                            .addComponent(cbb_searchby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pa_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_searchdata)
                            .addComponent(tf_searchdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btn_reset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pa_center.add(pa_search, "panel_search");

        pa_borrowNreturn.setBackground(new java.awt.Color(255, 204, 204));

        lb_tab_borrow.setBackground(new java.awt.Color(255, 204, 204));
        lb_tab_borrow.setFont(new java.awt.Font("Kanit", 0, 36)); // NOI18N
        lb_tab_borrow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_tab_borrow.setText("ยืมหนังสือ");
        lb_tab_borrow.setOpaque(true);
        lb_tab_borrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_tab_borrowMouseClicked(evt);
            }
        });

        lb_tab_return.setBackground(new java.awt.Color(153, 204, 255));
        lb_tab_return.setFont(new java.awt.Font("Kanit", 0, 36)); // NOI18N
        lb_tab_return.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_tab_return.setText("คืนหนังสือ");
        lb_tab_return.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lb_tab_return.setOpaque(true);
        lb_tab_return.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_tab_returnMouseClicked(evt);
            }
        });

        pa_borrowNreturn_cards.setBackground(pa_borrowNreturn.getBackground());
        pa_borrowNreturn_cards.setLayout(new java.awt.CardLayout());

        pa_borrow.setBackground(new java.awt.Color(255, 204, 204));

        lb_borrownumber1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_borrownumber1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_borrownumber1.setText("รหัสการยืม : ");

        tf_borrownumber1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_borrownumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_borrownumber1ActionPerformed(evt);
            }
        });

        lb_callnumber1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_callnumber1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_callnumber1.setText("รหัสเรียกหนังสือ : ");

        tf_callnumber1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_callnumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_callnumber1ActionPerformed(evt);
            }
        });

        lb_bookname1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_bookname1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_bookname1.setText("ชื่อหนังสือ : ");

        tf_bookname1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_bookname1.setEnabled(false);
        tf_bookname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_bookname1ActionPerformed(evt);
            }
        });

        lb_userid1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_userid1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_userid1.setText("รหัสผู้ยืม : ");

        tf_userid1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_userid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_userid1ActionPerformed(evt);
            }
        });

        lb_username1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_username1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_username1.setText("ชื่อผู้ยืม : ");

        tf_username1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_username1.setEnabled(false);
        tf_username1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_username1ActionPerformed(evt);
            }
        });

        cbb_borrowdays1.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        cbb_borrowdays1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- เลือกจำนวนวันที่ต้องการยืม --", "1 วัน", "3 วัน", "7 วัน", "14 วัน" }));
        cbb_borrowdays1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_borrowdays1ActionPerformed(evt);
            }
        });

        lb_borrowdays1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_borrowdays1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_borrowdays1.setText("จำนวนวันที่ยืม : ");

        tf_borrowdate1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_borrowdate1.setEnabled(false);
        tf_borrowdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_borrowdate1ActionPerformed(evt);
            }
        });

        lb_borrowdate1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_borrowdate1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_borrowdate1.setText("วันที่ยืม : ");

        lb_returndate1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_returndate1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_returndate1.setText("วันที่คืน : ");

        tf_returndate1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_returndate1.setEnabled(false);
        tf_returndate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_returndate1ActionPerformed(evt);
            }
        });

        lb_img_book1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_img_book1.setText("(รูปหนังสือ)");
        lb_img_book1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        btn_record_borrowing.setFont(new java.awt.Font("Kanit", 0, 36)); // NOI18N
        btn_record_borrowing.setText("บันทึกการยืมหนังสือ");

        javax.swing.GroupLayout pa_borrowLayout = new javax.swing.GroupLayout(pa_borrow);
        pa_borrow.setLayout(pa_borrowLayout);
        pa_borrowLayout.setHorizontalGroup(
            pa_borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa_borrowLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(pa_borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pa_borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pa_borrowLayout.createSequentialGroup()
                            .addComponent(lb_callnumber1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_callnumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pa_borrowLayout.createSequentialGroup()
                            .addComponent(lb_borrownumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_borrownumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pa_borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pa_borrowLayout.createSequentialGroup()
                            .addComponent(lb_userid1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_userid1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pa_borrowLayout.createSequentialGroup()
                            .addComponent(lb_bookname1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_bookname1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pa_borrowLayout.createSequentialGroup()
                            .addComponent(lb_username1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_username1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pa_borrowLayout.createSequentialGroup()
                            .addComponent(lb_borrowdays1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbb_borrowdays1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pa_borrowLayout.createSequentialGroup()
                            .addComponent(lb_borrowdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_borrowdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pa_borrowLayout.createSequentialGroup()
                            .addComponent(lb_returndate1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_returndate1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 145, Short.MAX_VALUE)
                .addComponent(lb_img_book1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(pa_borrowLayout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(btn_record_borrowing, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pa_borrowLayout.setVerticalGroup(
            pa_borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pa_borrowLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pa_borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_img_book1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pa_borrowLayout.createSequentialGroup()
                        .addGroup(pa_borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_borrownumber1)
                            .addComponent(lb_borrownumber1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pa_borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_callnumber1)
                            .addComponent(lb_callnumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pa_borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_bookname1)
                            .addComponent(lb_bookname1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pa_borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_userid1)
                            .addComponent(lb_userid1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pa_borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_username1)
                            .addComponent(lb_username1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pa_borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb_borrowdays1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbb_borrowdays1))
                        .addGap(18, 18, 18)
                        .addGroup(pa_borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_borrowdate1)
                            .addComponent(lb_borrowdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pa_borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_returndate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_returndate1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btn_record_borrowing)
                .addGap(30, 30, 30))
        );

        pa_borrowNreturn_cards.add(pa_borrow, "panel_borrow");

        pa_return.setBackground(new java.awt.Color(153, 204, 255));

        lb_borrownumber2.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_borrownumber2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_borrownumber2.setText("รหัสการยืม : ");

        tf_borrownumber2.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_borrownumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_borrownumber2ActionPerformed(evt);
            }
        });

        lb_callnumber2.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_callnumber2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_callnumber2.setText("รหัสเรียกหนังสือ : ");

        tf_callnumber2.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_callnumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_callnumber2ActionPerformed(evt);
            }
        });

        lb_bookname2.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_bookname2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_bookname2.setText("ชื่อหนังสือ : ");

        tf_bookname2.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_bookname2.setEnabled(false);
        tf_bookname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_bookname2ActionPerformed(evt);
            }
        });

        lb_userid2.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_userid2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_userid2.setText("รหัสผู้ยืม : ");

        tf_userid2.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_userid2.setEnabled(false);
        tf_userid2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_userid2ActionPerformed(evt);
            }
        });

        lb_username2.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_username2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_username2.setText("ชื่อผู้ยืม : ");

        tf_username2.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_username2.setEnabled(false);
        tf_username2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_username2ActionPerformed(evt);
            }
        });

        tf_borrowdate2.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_borrowdate2.setEnabled(false);
        tf_borrowdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_borrowdate2ActionPerformed(evt);
            }
        });

        lb_borrowdate2.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_borrowdate2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_borrowdate2.setText("วันที่ยืม : ");

        lb_returndate2.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_returndate2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_returndate2.setText("วันที่คืน : ");

        tf_returndate2.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_returndate2.setEnabled(false);
        tf_returndate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_returndate2ActionPerformed(evt);
            }
        });

        lb_img_book2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_img_book2.setText("(รูปหนังสือ)");
        lb_img_book2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        btn_record_returning.setFont(new java.awt.Font("Kanit", 0, 36)); // NOI18N
        btn_record_returning.setText("บันทึกการคืนหนังสือ");

        javax.swing.GroupLayout pa_returnLayout = new javax.swing.GroupLayout(pa_return);
        pa_return.setLayout(pa_returnLayout);
        pa_returnLayout.setHorizontalGroup(
            pa_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa_returnLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(pa_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pa_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pa_returnLayout.createSequentialGroup()
                            .addComponent(lb_callnumber2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_callnumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pa_returnLayout.createSequentialGroup()
                            .addComponent(lb_borrownumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_borrownumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pa_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pa_returnLayout.createSequentialGroup()
                            .addComponent(lb_userid2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_userid2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pa_returnLayout.createSequentialGroup()
                            .addComponent(lb_bookname2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_bookname2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pa_returnLayout.createSequentialGroup()
                            .addComponent(lb_username2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_username2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pa_returnLayout.createSequentialGroup()
                            .addComponent(lb_borrowdate2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_borrowdate2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pa_returnLayout.createSequentialGroup()
                            .addComponent(lb_returndate2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_returndate2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 145, Short.MAX_VALUE)
                .addComponent(lb_img_book2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(pa_returnLayout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(btn_record_returning, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pa_returnLayout.setVerticalGroup(
            pa_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pa_returnLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pa_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_img_book2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pa_returnLayout.createSequentialGroup()
                        .addGroup(pa_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_borrownumber2)
                            .addComponent(lb_borrownumber2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pa_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_callnumber2)
                            .addComponent(lb_callnumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pa_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_bookname2)
                            .addComponent(lb_bookname2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pa_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_userid2)
                            .addComponent(lb_userid2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pa_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_username2)
                            .addComponent(lb_username2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pa_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_borrowdate2)
                            .addComponent(lb_borrowdate2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pa_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_returndate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_returndate2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_record_returning)
                .addGap(30, 30, 30))
        );

        pa_borrowNreturn_cards.add(pa_return, "panel_return");

        javax.swing.GroupLayout pa_borrowNreturnLayout = new javax.swing.GroupLayout(pa_borrowNreturn);
        pa_borrowNreturn.setLayout(pa_borrowNreturnLayout);
        pa_borrowNreturnLayout.setHorizontalGroup(
            pa_borrowNreturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa_borrowNreturnLayout.createSequentialGroup()
                .addComponent(lb_tab_borrow, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lb_tab_return, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pa_borrowNreturn_cards, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pa_borrowNreturnLayout.setVerticalGroup(
            pa_borrowNreturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa_borrowNreturnLayout.createSequentialGroup()
                .addGroup(pa_borrowNreturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_tab_borrow, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_tab_return, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(pa_borrowNreturn_cards, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pa_center.add(pa_borrowNreturn, "panel_borrowNreturn");

        pa_history.setBackground(new java.awt.Color(255, 255, 153));

        JTable_borrowhistory.setAutoCreateRowSorter(true);
        JTable_borrowhistory.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        JTable_borrowhistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "รหัสการยืม", "รหัสหนังสือ", "ชื่อหนังสือ", "ชื่อผู้ยืม", "วันที่ยืม", "วันที่คืน"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(JTable_borrowhistory);

        jLabel1.setFont(new java.awt.Font("Kanit", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ประวัติการยืม-คืนหนังสือ");

        jLabel2.setBackground(new java.awt.Color(153, 255, 153));
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Kanit", 0, 24)); // NOI18N
        jLabel3.setText("คืนแล้ว");

        jLabel4.setBackground(new java.awt.Color(255, 153, 153));
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.setOpaque(true);

        jLabel5.setFont(new java.awt.Font("Kanit", 0, 24)); // NOI18N
        jLabel5.setText("ยังไม่คืน");

        javax.swing.GroupLayout pa_historyLayout = new javax.swing.GroupLayout(pa_history);
        pa_history.setLayout(pa_historyLayout);
        pa_historyLayout.setHorizontalGroup(
            pa_historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa_historyLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(pa_historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pa_historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE))
                    .addGroup(pa_historyLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        pa_historyLayout.setVerticalGroup(
            pa_historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pa_historyLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pa_historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pa_historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                    .addGroup(pa_historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pa_center.add(pa_history, "panel_history");

        pa_book.setBackground(new java.awt.Color(254, 193, 247));

        lb_tab_addbook.setBackground(new java.awt.Color(255, 204, 204));
        lb_tab_addbook.setFont(new java.awt.Font("Kanit", 0, 36)); // NOI18N
        lb_tab_addbook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_tab_addbook.setText("เพิ่มข้อมูลหนังสือ");
        lb_tab_addbook.setOpaque(true);
        lb_tab_addbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_tab_addbookMouseClicked(evt);
            }
        });

        lb_tab_removebook.setBackground(new java.awt.Color(153, 204, 255));
        lb_tab_removebook.setFont(new java.awt.Font("Kanit", 0, 36)); // NOI18N
        lb_tab_removebook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_tab_removebook.setText("ลบข้อมูลหนังสือ");
        lb_tab_removebook.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lb_tab_removebook.setOpaque(true);
        lb_tab_removebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_tab_removebookMouseClicked(evt);
            }
        });

        pa_book_cards.setBackground(pa_borrowNreturn.getBackground());
        pa_book_cards.setLayout(new java.awt.CardLayout());

        pa_addbook.setBackground(new java.awt.Color(255, 204, 204));

        lb_callnumber3.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_callnumber3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_callnumber3.setText("รหัสเรียกหนังสือ : ");

        tf_callnumber3.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_callnumber3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_callnumber3ActionPerformed(evt);
            }
        });

        lb_bookname3.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_bookname3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_bookname3.setText("ชื่อหนังสือ : ");

        tf_bookname3.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_bookname3.setEnabled(false);
        tf_bookname3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_bookname3ActionPerformed(evt);
            }
        });

        lb_img_book3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_img_book3.setText("(รูปหนังสือ)");
        lb_img_book3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        btn_addbook.setFont(new java.awt.Font("Kanit", 0, 36)); // NOI18N
        btn_addbook.setText("เพิ่มข้อมูลหนังสือ");

        lb_bookname5.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_bookname5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_bookname5.setText("รูปปกหนังสือ : ");

        btn_choosefile.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        btn_choosefile.setText("Choose File");
        btn_choosefile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_choosefileMouseClicked(evt);
            }
        });
        btn_choosefile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_choosefileActionPerformed(evt);
            }
        });

        lb_filename.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        lb_filename.setText("No file chosen");

        javax.swing.GroupLayout pa_addbookLayout = new javax.swing.GroupLayout(pa_addbook);
        pa_addbook.setLayout(pa_addbookLayout);
        pa_addbookLayout.setHorizontalGroup(
            pa_addbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa_addbookLayout.createSequentialGroup()
                .addGroup(pa_addbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pa_addbookLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(pa_addbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pa_addbookLayout.createSequentialGroup()
                                .addComponent(lb_callnumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_callnumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pa_addbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pa_addbookLayout.createSequentialGroup()
                                    .addComponent(lb_bookname3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_bookname3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pa_addbookLayout.createSequentialGroup()
                                    .addComponent(lb_bookname5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_choosefile, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pa_addbookLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_filename, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 145, Short.MAX_VALUE)
                .addComponent(lb_img_book3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(pa_addbookLayout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(btn_addbook, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pa_addbookLayout.setVerticalGroup(
            pa_addbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pa_addbookLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pa_addbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pa_addbookLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(pa_addbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_callnumber3)
                            .addComponent(lb_callnumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pa_addbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_bookname3)
                            .addComponent(lb_bookname3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pa_addbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_bookname5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_choosefile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_filename)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pa_addbookLayout.createSequentialGroup()
                        .addComponent(lb_img_book3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 85, Short.MAX_VALUE)))
                .addComponent(btn_addbook)
                .addGap(30, 30, 30))
        );

        pa_book_cards.add(pa_addbook, "panel_addbook");

        pa_removebook.setBackground(new java.awt.Color(153, 204, 255));

        lb_callnumber4.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_callnumber4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_callnumber4.setText("รหัสเรียกหนังสือ : ");

        tf_callnumber4.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_callnumber4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_callnumber4ActionPerformed(evt);
            }
        });

        lb_bookname4.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_bookname4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_bookname4.setText("ชื่อหนังสือ : ");

        tf_bookname4.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_bookname4.setEnabled(false);
        tf_bookname4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_bookname4ActionPerformed(evt);
            }
        });

        lb_img_book4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_img_book4.setText("(รูปหนังสือ)");
        lb_img_book4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        btn_removebook.setFont(new java.awt.Font("Kanit", 0, 36)); // NOI18N
        btn_removebook.setText("ลบข้อมูลหนังสือ");

        javax.swing.GroupLayout pa_removebookLayout = new javax.swing.GroupLayout(pa_removebook);
        pa_removebook.setLayout(pa_removebookLayout);
        pa_removebookLayout.setHorizontalGroup(
            pa_removebookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa_removebookLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(pa_removebookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pa_removebookLayout.createSequentialGroup()
                        .addComponent(lb_callnumber4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_callnumber4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pa_removebookLayout.createSequentialGroup()
                        .addComponent(lb_bookname4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_bookname4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 145, Short.MAX_VALUE)
                .addComponent(lb_img_book4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(pa_removebookLayout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(btn_removebook, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pa_removebookLayout.setVerticalGroup(
            pa_removebookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pa_removebookLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pa_removebookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_img_book4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pa_removebookLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(pa_removebookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_callnumber4)
                            .addComponent(lb_callnumber4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pa_removebookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_bookname4)
                            .addComponent(lb_bookname4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(btn_removebook)
                .addGap(30, 30, 30))
        );

        pa_book_cards.add(pa_removebook, "panel_removebook");

        javax.swing.GroupLayout pa_bookLayout = new javax.swing.GroupLayout(pa_book);
        pa_book.setLayout(pa_bookLayout);
        pa_bookLayout.setHorizontalGroup(
            pa_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa_bookLayout.createSequentialGroup()
                .addComponent(lb_tab_addbook, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lb_tab_removebook, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pa_book_cards, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pa_bookLayout.setVerticalGroup(
            pa_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa_bookLayout.createSequentialGroup()
                .addGroup(pa_bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_tab_addbook, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_tab_removebook, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(pa_book_cards, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pa_center.add(pa_book, "panel_book");

        getContentPane().add(pa_center, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_resetActionPerformed

    private void lb_tab_borrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_tab_borrowMouseClicked
        lb_tab_borrow.setBorder(null);
        lb_tab_return.setBorder(BorderFactory.createRaisedBevelBorder());
        CardLayout cl = (CardLayout)(pa_borrowNreturn_cards.getLayout());
        cl.show(pa_borrowNreturn_cards, "panel_borrow");
        System.out.println("Panel borrowNreturn cards: change to panel_borrow");
    }//GEN-LAST:event_lb_tab_borrowMouseClicked

    private void lb_tab_returnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_tab_returnMouseClicked
        lb_tab_borrow.setBorder(BorderFactory.createRaisedBevelBorder());
        lb_tab_return.setBorder(null);
        CardLayout cl = (CardLayout)(pa_borrowNreturn_cards.getLayout());
        cl.show(pa_borrowNreturn_cards, "panel_return");
        System.out.println("Panel borrowNreturn cards: change to panel_return");
    }//GEN-LAST:event_lb_tab_returnMouseClicked

    private void tf_borrownumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_borrownumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_borrownumber1ActionPerformed

    private void tf_callnumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_callnumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_callnumber1ActionPerformed

    private void tf_bookname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_bookname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_bookname1ActionPerformed

    private void tf_userid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_userid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_userid1ActionPerformed

    private void tf_username1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_username1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_username1ActionPerformed

    private void tf_borrowdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_borrowdate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_borrowdate1ActionPerformed

    private void tf_returndate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_returndate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_returndate1ActionPerformed

    private void tf_borrownumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_borrownumber2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_borrownumber2ActionPerformed

    private void tf_callnumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_callnumber2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_callnumber2ActionPerformed

    private void tf_bookname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_bookname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_bookname2ActionPerformed

    private void tf_userid2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_userid2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_userid2ActionPerformed

    private void tf_username2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_username2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_username2ActionPerformed

    private void tf_borrowdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_borrowdate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_borrowdate2ActionPerformed

    private void tf_returndate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_returndate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_returndate2ActionPerformed

    private void cbb_borrowdays1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_borrowdays1ActionPerformed
       int cbb_index = cbb_borrowdays1.getSelectedIndex();
       currentCal = Calendar.getInstance();
       if (cbb_index > 0) {
           switch (cbb_index){
                case 1: currentCal.add(Calendar.DATE, 1); break;
                case 2: currentCal.add(Calendar.DATE, 3); break;
                case 3: currentCal.add(Calendar.DATE, 7); break;
                case 4: currentCal.add(Calendar.DATE, 14); break;
            }
        toDate = dateFormat.format(currentCal.getTime());
        tf_returndate1.setText(toDate);
       }
       
    }//GEN-LAST:event_cbb_borrowdays1ActionPerformed

    
    private void lb_tab_addbookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_tab_addbookMouseClicked
        lb_tab_addbook.setBorder(null);
        lb_tab_removebook.setBorder(BorderFactory.createRaisedBevelBorder());
        CardLayout cl = (CardLayout)(pa_book_cards.getLayout());
        cl.show(pa_book_cards, "panel_addbook");
        System.out.println("Panel book cards: change to panel_addbook");
    }//GEN-LAST:event_lb_tab_addbookMouseClicked

    private void lb_tab_removebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_tab_removebookMouseClicked
        lb_tab_removebook.setBorder(null);
        lb_tab_addbook.setBorder(BorderFactory.createRaisedBevelBorder());
        CardLayout cl = (CardLayout)(pa_book_cards.getLayout());
        cl.show(pa_book_cards, "panel_removebook");
        System.out.println("Panel book cards: change to panel_removebook");
    }//GEN-LAST:event_lb_tab_removebookMouseClicked

    private void tf_callnumber4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_callnumber4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_callnumber4ActionPerformed

    private void tf_bookname4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_bookname4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_bookname4ActionPerformed

    private void tf_bookname3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_bookname3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_bookname3ActionPerformed

    private void tf_callnumber3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_callnumber3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_callnumber3ActionPerformed

    private void btn_choosefileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_choosefileActionPerformed
        int result = file.showOpenDialog(null);
        //if the user click on open in Jfilechooser
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            String filename = selectedFile.getName();
            System.out.println("Chosen file path: " + path);
            lb_filename.setText(filename);
            
            ImageIcon img_book_chosen = new ImageIcon(new ImageIcon(path).getImage().getScaledInstance(300, 400, Image.SCALE_SMOOTH));
            lb_img_book3.setIcon(img_book_chosen);
        } else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("No File Select");
        }
    }//GEN-LAST:event_btn_choosefileActionPerformed

    private void btn_choosefileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_choosefileMouseClicked

    }//GEN-LAST:event_btn_choosefileMouseClicked

    private void lb_menu_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_searchMouseClicked
        pa_center_changeto("panel_search");
    }//GEN-LAST:event_lb_menu_searchMouseClicked

    private void lb_menu_borrowNreturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_borrowNreturnMouseClicked
        pa_center_changeto("panel_borrowNreturn");
    }//GEN-LAST:event_lb_menu_borrowNreturnMouseClicked

    private void lb_menu_historyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_historyMouseClicked
        pa_center_changeto("panel_history");
    }//GEN-LAST:event_lb_menu_historyMouseClicked

    private void lb_menu_bookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_bookMouseClicked
        pa_center_changeto("panel_book");
    }//GEN-LAST:event_lb_menu_bookMouseClicked

    private void lb_menu_searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_searchMouseEntered
        lb_menu_mouseentered(evt);
    }//GEN-LAST:event_lb_menu_searchMouseEntered

    private void lb_menu_searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_searchMouseExited
        lb_menu_mouseexited(evt);
    }//GEN-LAST:event_lb_menu_searchMouseExited

    private void lb_menu_borrowNreturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_borrowNreturnMouseEntered
        lb_menu_mouseentered(evt);
    }//GEN-LAST:event_lb_menu_borrowNreturnMouseEntered

    private void lb_menu_borrowNreturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_borrowNreturnMouseExited
        lb_menu_mouseexited(evt);
    }//GEN-LAST:event_lb_menu_borrowNreturnMouseExited

    private void lb_menu_historyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_historyMouseEntered
        lb_menu_mouseentered(evt);
    }//GEN-LAST:event_lb_menu_historyMouseEntered

    private void lb_menu_historyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_historyMouseExited
        lb_menu_mouseexited(evt);
    }//GEN-LAST:event_lb_menu_historyMouseExited

    private void lb_menu_bookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_bookMouseEntered
        lb_menu_mouseentered(evt);
    }//GEN-LAST:event_lb_menu_bookMouseEntered

    private void lb_menu_bookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_bookMouseExited
        lb_menu_mouseexited(evt);
    }//GEN-LAST:event_lb_menu_bookMouseExited

    private void lb_menu_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_logoutMouseClicked
        GuiInit.initLoginForm();
        this.dispose();
    }//GEN-LAST:event_lb_menu_logoutMouseClicked

    private void lb_menu_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_logoutMouseEntered
        lb_menu_mouseentered(evt);
    }//GEN-LAST:event_lb_menu_logoutMouseEntered

    private void lb_menu_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_logoutMouseExited
        lb_menu_mouseexited(evt);
    }//GEN-LAST:event_lb_menu_logoutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTable_bookinfo;
    private javax.swing.JTable JTable_borrowhistory;
    private javax.swing.JButton btn_addbook;
    private javax.swing.JButton btn_choosefile;
    private javax.swing.JButton btn_record_borrowing;
    private javax.swing.JButton btn_record_returning;
    private javax.swing.JButton btn_removebook;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_search;
    private javax.swing.JComboBox<String> cbb_borrowdays1;
    private javax.swing.JComboBox<String> cbb_searchby;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_ADMIN;
    private javax.swing.JLabel lb_bookname1;
    private javax.swing.JLabel lb_bookname2;
    private javax.swing.JLabel lb_bookname3;
    private javax.swing.JLabel lb_bookname4;
    private javax.swing.JLabel lb_bookname5;
    private javax.swing.JLabel lb_borrowdate1;
    private javax.swing.JLabel lb_borrowdate2;
    private javax.swing.JLabel lb_borrowdays1;
    private javax.swing.JLabel lb_borrownumber1;
    private javax.swing.JLabel lb_borrownumber2;
    private javax.swing.JLabel lb_callnumber1;
    private javax.swing.JLabel lb_callnumber2;
    private javax.swing.JLabel lb_callnumber3;
    private javax.swing.JLabel lb_callnumber4;
    private javax.swing.JLabel lb_filename;
    private javax.swing.JLabel lb_img_book1;
    private javax.swing.JLabel lb_img_book2;
    private javax.swing.JLabel lb_img_book3;
    private javax.swing.JLabel lb_img_book4;
    private javax.swing.JLabel lb_menu_book;
    private javax.swing.JLabel lb_menu_borrowNreturn;
    private javax.swing.JLabel lb_menu_history;
    private javax.swing.JLabel lb_menu_logout;
    private javax.swing.JLabel lb_menu_search;
    private javax.swing.JLabel lb_returndate1;
    private javax.swing.JLabel lb_returndate2;
    private javax.swing.JLabel lb_searchby;
    private javax.swing.JLabel lb_searchdata;
    private javax.swing.JLabel lb_tab_addbook;
    private javax.swing.JLabel lb_tab_borrow;
    private javax.swing.JLabel lb_tab_removebook;
    private javax.swing.JLabel lb_tab_return;
    private javax.swing.JLabel lb_userid1;
    private javax.swing.JLabel lb_userid2;
    private javax.swing.JLabel lb_username1;
    private javax.swing.JLabel lb_username2;
    private javax.swing.JPanel pa_addbook;
    private javax.swing.JPanel pa_book;
    private javax.swing.JPanel pa_book_cards;
    private javax.swing.JPanel pa_borrow;
    private javax.swing.JPanel pa_borrowNreturn;
    private javax.swing.JPanel pa_borrowNreturn_cards;
    private javax.swing.JPanel pa_center;
    private javax.swing.JPanel pa_history;
    private javax.swing.JPanel pa_menu;
    private javax.swing.JPanel pa_removebook;
    private javax.swing.JPanel pa_return;
    private javax.swing.JPanel pa_search;
    private javax.swing.JTextField tf_bookname1;
    private javax.swing.JTextField tf_bookname2;
    private javax.swing.JTextField tf_bookname3;
    private javax.swing.JTextField tf_bookname4;
    private javax.swing.JTextField tf_borrowdate1;
    private javax.swing.JTextField tf_borrowdate2;
    private javax.swing.JTextField tf_borrownumber1;
    private javax.swing.JTextField tf_borrownumber2;
    private javax.swing.JTextField tf_callnumber1;
    private javax.swing.JTextField tf_callnumber2;
    private javax.swing.JTextField tf_callnumber3;
    private javax.swing.JTextField tf_callnumber4;
    private javax.swing.JTextField tf_returndate1;
    private javax.swing.JTextField tf_returndate2;
    private javax.swing.JTextField tf_searchdata;
    private javax.swing.JTextField tf_userid1;
    private javax.swing.JTextField tf_userid2;
    private javax.swing.JTextField tf_username1;
    private javax.swing.JTextField tf_username2;
    // End of variables declaration//GEN-END:variables
}
