/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.BorderFactory;

/**
 *
 * @author IsilenceT
 */
public class AdminBorrowNreturn extends javax.swing.JPanel {

    private SimpleDateFormat dateFormat;
    private Calendar currentCal;
    private String currentdate, toDate;
    
    
    /**
     * Creates new form AdminBorrowNreturn
     */
    public AdminBorrowNreturn() {
        initComponents();
        
        dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        currentCal = Calendar.getInstance();
        currentdate = dateFormat.format(currentCal.getTime());
        tf_borrowdate1.setText(currentdate);
    }
    
    public void getBorrowPanel(String panel_name){
        CardLayout brcards = (CardLayout)(pa_borrowNreturn_cards.getLayout());
        brcards.show(pa_borrowNreturn_cards, panel_name);
        System.out.println("Panel borrowNreturn cards: change to " + panel_name);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_tab_borrow = new javax.swing.JLabel();
        lb_tab_return = new javax.swing.JLabel();
        pa_borrowNreturn_cards = new javax.swing.JPanel();
        pa_borrow = new javax.swing.JPanel();
        lb_borrownumber1 = new javax.swing.JLabel();
        tf_borrownumber1 = new javax.swing.JTextField();
        lb_callnumber1 = new javax.swing.JLabel();
        tf_callnumber1 = new javax.swing.JTextField();
        lb_bookname1 = new javax.swing.JLabel();
        tf_bookname1 = new javax.swing.JTextField();
        lb_userid1 = new javax.swing.JLabel();
        tf_userid1 = new javax.swing.JTextField();
        lb_username1 = new javax.swing.JLabel();
        tf_username1 = new javax.swing.JTextField();
        cbb_borrowdays1 = new javax.swing.JComboBox<>();
        lb_borrowdays1 = new javax.swing.JLabel();
        tf_borrowdate1 = new javax.swing.JTextField();
        lb_borrowdate1 = new javax.swing.JLabel();
        lb_returndate1 = new javax.swing.JLabel();
        tf_returndate1 = new javax.swing.JTextField();
        lb_img_book1 = new javax.swing.JLabel();
        btn_record_borrowing = new javax.swing.JButton();
        pa_return = new javax.swing.JPanel();
        lb_borrownumber2 = new javax.swing.JLabel();
        tf_borrownumber2 = new javax.swing.JTextField();
        lb_callnumber2 = new javax.swing.JLabel();
        tf_callnumber2 = new javax.swing.JTextField();
        lb_bookname2 = new javax.swing.JLabel();
        tf_bookname2 = new javax.swing.JTextField();
        lb_userid2 = new javax.swing.JLabel();
        tf_userid2 = new javax.swing.JTextField();
        lb_username2 = new javax.swing.JLabel();
        tf_username2 = new javax.swing.JTextField();
        tf_borrowdate2 = new javax.swing.JTextField();
        lb_borrowdate2 = new javax.swing.JLabel();
        lb_returndate2 = new javax.swing.JLabel();
        tf_returndate2 = new javax.swing.JTextField();
        lb_img_book2 = new javax.swing.JLabel();
        btn_record_returning = new javax.swing.JButton();

        lb_tab_borrow.setBackground(new java.awt.Color(255, 204, 204));
        lb_tab_borrow.setFont(new java.awt.Font("Kanit", 0, 36)); // NOI18N
        lb_tab_borrow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_tab_borrow.setText("ยืมหนังสือ");
        lb_tab_borrow.setOpaque(true);
        lb_tab_borrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_tab_borrowMouseClicked(evt);
            }
        });

        lb_tab_return.setBackground(new java.awt.Color(153, 204, 255));
        lb_tab_return.setFont(new java.awt.Font("Kanit", 0, 36)); // NOI18N
        lb_tab_return.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_tab_return.setText("คืนหนังสือ");
        lb_tab_return.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lb_tab_return.setOpaque(true);
        lb_tab_return.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_tab_returnMouseClicked(evt);
            }
        });

        pa_borrowNreturn_cards.setLayout(new java.awt.CardLayout());

        pa_borrow.setBackground(new java.awt.Color(255, 204, 204));

        lb_borrownumber1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_borrownumber1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_borrownumber1.setText("รหัสการยืม : ");

        tf_borrownumber1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_borrownumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_borrownumber1ActionPerformed(evt);
            }
        });

        lb_callnumber1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_callnumber1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_callnumber1.setText("รหัสเรียกหนังสือ : ");

        tf_callnumber1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_callnumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_callnumber1ActionPerformed(evt);
            }
        });

        lb_bookname1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_bookname1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_bookname1.setText("ชื่อหนังสือ : ");

        tf_bookname1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_bookname1.setEnabled(false);
        tf_bookname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_bookname1ActionPerformed(evt);
            }
        });

        lb_userid1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_userid1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_userid1.setText("รหัสผู้ยืม : ");

        tf_userid1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_userid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_userid1ActionPerformed(evt);
            }
        });

        lb_username1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_username1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_username1.setText("ชื่อผู้ยืม : ");

        tf_username1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_username1.setEnabled(false);
        tf_username1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_username1ActionPerformed(evt);
            }
        });

        cbb_borrowdays1.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        cbb_borrowdays1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- เลือกจำนวนวันที่ต้องการยืม --", "1 วัน", "3 วัน", "7 วัน", "14 วัน" }));
        cbb_borrowdays1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_borrowdays1ActionPerformed(evt);
            }
        });

        lb_borrowdays1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_borrowdays1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_borrowdays1.setText("จำนวนวันที่ยืม : ");

        tf_borrowdate1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_borrowdate1.setEnabled(false);
        tf_borrowdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_borrowdate1ActionPerformed(evt);
            }
        });

        lb_borrowdate1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_borrowdate1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_borrowdate1.setText("วันที่ยืม : ");

        lb_returndate1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_returndate1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_returndate1.setText("วันที่คืน : ");

        tf_returndate1.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_returndate1.setEnabled(false);
        tf_returndate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_returndate1ActionPerformed(evt);
            }
        });

        lb_img_book1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_img_book1.setText("(รูปหนังสือ)");
        lb_img_book1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        btn_record_borrowing.setFont(new java.awt.Font("Kanit", 0, 36)); // NOI18N
        btn_record_borrowing.setText("บันทึกการยืมหนังสือ");

        javax.swing.GroupLayout pa_borrowLayout = new javax.swing.GroupLayout(pa_borrow);
        pa_borrow.setLayout(pa_borrowLayout);
        pa_borrowLayout.setHorizontalGroup(
            pa_borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa_borrowLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(pa_borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pa_borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pa_borrowLayout.createSequentialGroup()
                            .addComponent(lb_callnumber1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_callnumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pa_borrowLayout.createSequentialGroup()
                            .addComponent(lb_borrownumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_borrownumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pa_borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pa_borrowLayout.createSequentialGroup()
                            .addComponent(lb_userid1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_userid1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pa_borrowLayout.createSequentialGroup()
                            .addComponent(lb_bookname1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_bookname1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pa_borrowLayout.createSequentialGroup()
                            .addComponent(lb_username1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_username1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pa_borrowLayout.createSequentialGroup()
                            .addComponent(lb_borrowdays1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbb_borrowdays1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pa_borrowLayout.createSequentialGroup()
                            .addComponent(lb_borrowdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_borrowdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pa_borrowLayout.createSequentialGroup()
                            .addComponent(lb_returndate1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_returndate1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 145, Short.MAX_VALUE)
                .addComponent(lb_img_book1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(pa_borrowLayout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(btn_record_borrowing, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pa_borrowLayout.setVerticalGroup(
            pa_borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pa_borrowLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pa_borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_img_book1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pa_borrowLayout.createSequentialGroup()
                        .addGroup(pa_borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_borrownumber1)
                            .addComponent(lb_borrownumber1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pa_borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_callnumber1)
                            .addComponent(lb_callnumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pa_borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_bookname1)
                            .addComponent(lb_bookname1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pa_borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_userid1)
                            .addComponent(lb_userid1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pa_borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_username1)
                            .addComponent(lb_username1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pa_borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb_borrowdays1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbb_borrowdays1))
                        .addGap(18, 18, 18)
                        .addGroup(pa_borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_borrowdate1)
                            .addComponent(lb_borrowdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pa_borrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_returndate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_returndate1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btn_record_borrowing)
                .addGap(30, 30, 30))
        );

        pa_borrowNreturn_cards.add(pa_borrow, "panel_borrow");

        pa_return.setBackground(new java.awt.Color(153, 204, 255));

        lb_borrownumber2.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_borrownumber2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_borrownumber2.setText("รหัสการยืม : ");

        tf_borrownumber2.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_borrownumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_borrownumber2ActionPerformed(evt);
            }
        });

        lb_callnumber2.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_callnumber2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_callnumber2.setText("รหัสเรียกหนังสือ : ");

        tf_callnumber2.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_callnumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_callnumber2ActionPerformed(evt);
            }
        });

        lb_bookname2.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_bookname2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_bookname2.setText("ชื่อหนังสือ : ");

        tf_bookname2.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_bookname2.setEnabled(false);
        tf_bookname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_bookname2ActionPerformed(evt);
            }
        });

        lb_userid2.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_userid2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_userid2.setText("รหัสผู้ยืม : ");

        tf_userid2.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_userid2.setEnabled(false);
        tf_userid2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_userid2ActionPerformed(evt);
            }
        });

        lb_username2.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_username2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_username2.setText("ชื่อผู้ยืม : ");

        tf_username2.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_username2.setEnabled(false);
        tf_username2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_username2ActionPerformed(evt);
            }
        });

        tf_borrowdate2.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_borrowdate2.setEnabled(false);
        tf_borrowdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_borrowdate2ActionPerformed(evt);
            }
        });

        lb_borrowdate2.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_borrowdate2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_borrowdate2.setText("วันที่ยืม : ");

        lb_returndate2.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        lb_returndate2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_returndate2.setText("วันที่คืน : ");

        tf_returndate2.setFont(new java.awt.Font("Kanit", 0, 20)); // NOI18N
        tf_returndate2.setEnabled(false);
        tf_returndate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_returndate2ActionPerformed(evt);
            }
        });

        lb_img_book2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_img_book2.setText("(รูปหนังสือ)");
        lb_img_book2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        btn_record_returning.setFont(new java.awt.Font("Kanit", 0, 36)); // NOI18N
        btn_record_returning.setText("บันทึกการคืนหนังสือ");

        javax.swing.GroupLayout pa_returnLayout = new javax.swing.GroupLayout(pa_return);
        pa_return.setLayout(pa_returnLayout);
        pa_returnLayout.setHorizontalGroup(
            pa_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa_returnLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(pa_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pa_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pa_returnLayout.createSequentialGroup()
                            .addComponent(lb_callnumber2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_callnumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pa_returnLayout.createSequentialGroup()
                            .addComponent(lb_borrownumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_borrownumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pa_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pa_returnLayout.createSequentialGroup()
                            .addComponent(lb_userid2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_userid2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pa_returnLayout.createSequentialGroup()
                            .addComponent(lb_bookname2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_bookname2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pa_returnLayout.createSequentialGroup()
                            .addComponent(lb_username2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_username2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pa_returnLayout.createSequentialGroup()
                            .addComponent(lb_borrowdate2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_borrowdate2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pa_returnLayout.createSequentialGroup()
                            .addComponent(lb_returndate2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_returndate2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 145, Short.MAX_VALUE)
                .addComponent(lb_img_book2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(pa_returnLayout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(btn_record_returning, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pa_returnLayout.setVerticalGroup(
            pa_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pa_returnLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pa_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_img_book2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pa_returnLayout.createSequentialGroup()
                        .addGroup(pa_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_borrownumber2)
                            .addComponent(lb_borrownumber2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pa_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_callnumber2)
                            .addComponent(lb_callnumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pa_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_bookname2)
                            .addComponent(lb_bookname2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pa_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_userid2)
                            .addComponent(lb_userid2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pa_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_username2)
                            .addComponent(lb_username2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pa_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_borrowdate2)
                            .addComponent(lb_borrowdate2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pa_returnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_returndate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_returndate2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_record_returning)
                .addGap(30, 30, 30))
        );

        pa_borrowNreturn_cards.add(pa_return, "panel_return");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lb_tab_borrow, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lb_tab_return, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pa_borrowNreturn_cards, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_tab_borrow, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_tab_return, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(pa_borrowNreturn_cards, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lb_tab_borrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_tab_borrowMouseClicked
        lb_tab_borrow.setBorder(null);
        lb_tab_return.setBorder(BorderFactory.createRaisedBevelBorder());
        getBorrowPanel("panel_borrow");
    }//GEN-LAST:event_lb_tab_borrowMouseClicked

    private void lb_tab_returnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_tab_returnMouseClicked
        lb_tab_borrow.setBorder(BorderFactory.createRaisedBevelBorder());
        lb_tab_return.setBorder(null);
        getBorrowPanel("panel_return");
    }//GEN-LAST:event_lb_tab_returnMouseClicked

    private void tf_borrownumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_borrownumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_borrownumber1ActionPerformed

    private void tf_callnumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_callnumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_callnumber1ActionPerformed

    private void tf_bookname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_bookname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_bookname1ActionPerformed

    private void tf_userid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_userid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_userid1ActionPerformed

    private void tf_username1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_username1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_username1ActionPerformed

    private void cbb_borrowdays1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_borrowdays1ActionPerformed
        int cbb_index = cbb_borrowdays1.getSelectedIndex();
        currentCal = Calendar.getInstance();
        if (cbb_index > 0) {
            switch (cbb_index){
                case 1: currentCal.add(Calendar.DATE, 1); break;
                case 2: currentCal.add(Calendar.DATE, 3); break;
                case 3: currentCal.add(Calendar.DATE, 7); break;
                case 4: currentCal.add(Calendar.DATE, 14); break;
            }
            toDate = dateFormat.format(currentCal.getTime());
            tf_returndate1.setText(toDate);
        }

    }//GEN-LAST:event_cbb_borrowdays1ActionPerformed

    private void tf_borrowdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_borrowdate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_borrowdate1ActionPerformed

    private void tf_returndate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_returndate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_returndate1ActionPerformed

    private void tf_borrownumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_borrownumber2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_borrownumber2ActionPerformed

    private void tf_callnumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_callnumber2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_callnumber2ActionPerformed

    private void tf_bookname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_bookname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_bookname2ActionPerformed

    private void tf_userid2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_userid2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_userid2ActionPerformed

    private void tf_username2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_username2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_username2ActionPerformed

    private void tf_borrowdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_borrowdate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_borrowdate2ActionPerformed

    private void tf_returndate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_returndate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_returndate2ActionPerformed

    
    //variable name -> 1 = panel_borrow, 2 = panel_return
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_record_borrowing;
    private javax.swing.JButton btn_record_returning;
    private javax.swing.JComboBox<String> cbb_borrowdays1;
    private javax.swing.JLabel lb_bookname1;
    private javax.swing.JLabel lb_bookname2;
    private javax.swing.JLabel lb_borrowdate1;
    private javax.swing.JLabel lb_borrowdate2;
    private javax.swing.JLabel lb_borrowdays1;
    private javax.swing.JLabel lb_borrownumber1;
    private javax.swing.JLabel lb_borrownumber2;
    private javax.swing.JLabel lb_callnumber1;
    private javax.swing.JLabel lb_callnumber2;
    private javax.swing.JLabel lb_img_book1;
    private javax.swing.JLabel lb_img_book2;
    private javax.swing.JLabel lb_returndate1;
    private javax.swing.JLabel lb_returndate2;
    private javax.swing.JLabel lb_tab_borrow;
    private javax.swing.JLabel lb_tab_return;
    private javax.swing.JLabel lb_userid1;
    private javax.swing.JLabel lb_userid2;
    private javax.swing.JLabel lb_username1;
    private javax.swing.JLabel lb_username2;
    private javax.swing.JPanel pa_borrow;
    private javax.swing.JPanel pa_borrowNreturn_cards;
    private javax.swing.JPanel pa_return;
    private javax.swing.JTextField tf_bookname1;
    private javax.swing.JTextField tf_bookname2;
    private javax.swing.JTextField tf_borrowdate1;
    private javax.swing.JTextField tf_borrowdate2;
    private javax.swing.JTextField tf_borrownumber1;
    private javax.swing.JTextField tf_borrownumber2;
    private javax.swing.JTextField tf_callnumber1;
    private javax.swing.JTextField tf_callnumber2;
    private javax.swing.JTextField tf_returndate1;
    private javax.swing.JTextField tf_returndate2;
    private javax.swing.JTextField tf_userid1;
    private javax.swing.JTextField tf_userid2;
    private javax.swing.JTextField tf_username1;
    private javax.swing.JTextField tf_username2;
    // End of variables declaration//GEN-END:variables
}
