/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author IsilenceT
 */
public class AdminMenu extends javax.swing.JPanel {

    /**
     * Creates new form AdminMenu
     */
    
    public AdminMenu() {
        initComponents();
        
        ImageIcon icon_search = new ImageIcon(new ImageIcon(getClass().getResource("../image/icon_search.png")).getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH));
        lb_menu_search.setIcon(icon_search);

        ImageIcon icon_borrowNreturn = new ImageIcon(new ImageIcon(getClass().getResource("../image/icon_borrow.png")).getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH));
        lb_menu_borrowNreturn.setIcon(icon_borrowNreturn);

        ImageIcon icon_borrowhistory = new ImageIcon(new ImageIcon(getClass().getResource("../image/icon_borrowhistory.png")).getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH));
        lb_menu_history.setIcon(icon_borrowhistory);

        ImageIcon icon_book = new ImageIcon(new ImageIcon(getClass().getResource("../image/icon_book.png")).getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH));
        lb_menu_book.setIcon(icon_book);
        
        ImageIcon icon_logout = new ImageIcon(new ImageIcon(getClass().getResource("../image/icon_logout.png")).getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH));
        lb_menu_logout.setIcon(icon_logout);
        
    }

    public void lb_menu_mouseentered(MouseEvent evt){
        ((JLabel) evt.getSource()).setForeground(Color.red);
    }
    
    public void lb_menu_mouseexited(MouseEvent evt){
        ((JLabel) evt.getSource()).setForeground(Color.black);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_ADMIN = new javax.swing.JLabel();
        lb_menu_search = new javax.swing.JLabel();
        lb_menu_borrowNreturn = new javax.swing.JLabel();
        lb_menu_history = new javax.swing.JLabel();
        lb_menu_book = new javax.swing.JLabel();
        lb_menu_logout = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));

        lb_ADMIN.setBackground(new java.awt.Color(153, 255, 204));
        lb_ADMIN.setFont(new java.awt.Font("Kanit", 1, 36)); // NOI18N
        lb_ADMIN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_ADMIN.setText("ADMIN");
        lb_ADMIN.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.black));
        lb_ADMIN.setOpaque(true);

        lb_menu_search.setFont(new java.awt.Font("Kanit", 0, 24)); // NOI18N
        lb_menu_search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_menu_search.setText("ค้นหาหนังสือ");
        lb_menu_search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_menu_search.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_menu_search.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lb_menu_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_menu_searchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_menu_searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_menu_searchMouseExited(evt);
            }
        });

        lb_menu_borrowNreturn.setFont(new java.awt.Font("Kanit", 0, 24)); // NOI18N
        lb_menu_borrowNreturn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_menu_borrowNreturn.setText("<html><body style=\"text-align: center\">ทำรายการ<br>ยืม-คืนหนังสือ</body></html>");
        lb_menu_borrowNreturn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_menu_borrowNreturn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_menu_borrowNreturn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lb_menu_borrowNreturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_menu_borrowNreturnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_menu_borrowNreturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_menu_borrowNreturnMouseExited(evt);
            }
        });

        lb_menu_history.setFont(new java.awt.Font("Kanit", 0, 24)); // NOI18N
        lb_menu_history.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_menu_history.setText("<html><body style=\"text-align: center\">ประวัติการ<br>ยืม-คืนหนังสือ</body></html>");
        lb_menu_history.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_menu_history.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_menu_history.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lb_menu_history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_menu_historyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_menu_historyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_menu_historyMouseExited(evt);
            }
        });

        lb_menu_book.setFont(new java.awt.Font("Kanit", 0, 24)); // NOI18N
        lb_menu_book.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_menu_book.setText("ทะเบียนหนังสือ");
        lb_menu_book.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_menu_book.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_menu_book.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lb_menu_book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_menu_bookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_menu_bookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_menu_bookMouseExited(evt);
            }
        });

        lb_menu_logout.setFont(new java.awt.Font("Kanit", 0, 24)); // NOI18N
        lb_menu_logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_menu_logout.setText("Logout");
        lb_menu_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_menu_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_menu_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_menu_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_menu_logoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_ADMIN, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(lb_menu_borrowNreturn)
            .addComponent(lb_menu_search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_menu_book, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_menu_history, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(lb_menu_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lb_ADMIN, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_menu_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_menu_borrowNreturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_menu_history)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_menu_book, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(57, 57, 57)
                .addComponent(lb_menu_logout)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lb_menu_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_searchMouseClicked
        AdminGUI.getCenterPanel("panel_search");
    }//GEN-LAST:event_lb_menu_searchMouseClicked

    private void lb_menu_searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_searchMouseEntered
        lb_menu_mouseentered(evt);
    }//GEN-LAST:event_lb_menu_searchMouseEntered

    private void lb_menu_searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_searchMouseExited
        lb_menu_mouseexited(evt);
    }//GEN-LAST:event_lb_menu_searchMouseExited

    private void lb_menu_borrowNreturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_borrowNreturnMouseClicked
        AdminGUI.getCenterPanel("panel_borrowNreturn");
    }//GEN-LAST:event_lb_menu_borrowNreturnMouseClicked

    private void lb_menu_borrowNreturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_borrowNreturnMouseEntered
        lb_menu_mouseentered(evt);
    }//GEN-LAST:event_lb_menu_borrowNreturnMouseEntered

    private void lb_menu_borrowNreturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_borrowNreturnMouseExited
        lb_menu_mouseexited(evt);
    }//GEN-LAST:event_lb_menu_borrowNreturnMouseExited

    private void lb_menu_historyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_historyMouseClicked
        AdminGUI.getCenterPanel("panel_history");
    }//GEN-LAST:event_lb_menu_historyMouseClicked

    private void lb_menu_historyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_historyMouseEntered
        lb_menu_mouseentered(evt);
    }//GEN-LAST:event_lb_menu_historyMouseEntered

    private void lb_menu_historyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_historyMouseExited
        lb_menu_mouseexited(evt);
    }//GEN-LAST:event_lb_menu_historyMouseExited

    private void lb_menu_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_logoutMouseClicked
        AdminGUI.logout();
    }//GEN-LAST:event_lb_menu_logoutMouseClicked

    private void lb_menu_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_logoutMouseEntered
        lb_menu_mouseentered(evt);
    }//GEN-LAST:event_lb_menu_logoutMouseEntered

    private void lb_menu_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_logoutMouseExited
        lb_menu_mouseexited(evt);
    }//GEN-LAST:event_lb_menu_logoutMouseExited

    private void lb_menu_bookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_bookMouseExited
        lb_menu_mouseexited(evt);
    }//GEN-LAST:event_lb_menu_bookMouseExited

    private void lb_menu_bookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_bookMouseEntered
        lb_menu_mouseentered(evt);
    }//GEN-LAST:event_lb_menu_bookMouseEntered

    private void lb_menu_bookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_menu_bookMouseClicked
        AdminGUI.getCenterPanel("panel_book");
    }//GEN-LAST:event_lb_menu_bookMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb_ADMIN;
    private javax.swing.JLabel lb_menu_book;
    private javax.swing.JLabel lb_menu_borrowNreturn;
    private javax.swing.JLabel lb_menu_history;
    private javax.swing.JLabel lb_menu_logout;
    private javax.swing.JLabel lb_menu_search;
    // End of variables declaration//GEN-END:variables
}
