package gui;

import database.Connect;
import javax.swing.*;
import java.io.*;
import java.sql.*;

public class LoginForm extends javax.swing.JFrame {
  
    public LoginForm() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    
    public void save_rememberme_handle(){
        try (FileOutputStream fout = new FileOutputStream("rememberMe.dat");
             DataOutputStream dout = new DataOutputStream(fout);) {
            if (cb_rememberme.isSelected()) {
                dout.writeUTF("remember=" + tf_username.getText() + "=" + pf_password.getText());
            } else {
                dout.writeUTF("");
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
    
    public void get_rememberme_handle(){
        File f = new File("rememberMe.dat");
        if (f.exists()) {
            try (FileInputStream fin = new FileInputStream(f);
                 DataInputStream din = new DataInputStream(fin);) {
                String[] text_remember = din.readUTF().split("=");
                if (text_remember[0].equals("remember"))
                   cb_rememberme.setSelected(true);
                
                tf_username.setText(text_remember[1]);
                pf_password.setText(text_remember[2]);
                
                System.out.println("getRememberMe: username=" + text_remember[1] + ", password=" + text_remember[2]);
            } catch (IOException ex) {
                ex.printStackTrace();
            } catch (ArrayIndexOutOfBoundsException ex) {
                System.out.println("No remembered username or password");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pa_top = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        pa_center = new javax.swing.JPanel();
        lb_username = new javax.swing.JLabel();
        lb_password = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        tf_username = new javax.swing.JTextField();
        pf_password = new javax.swing.JPasswordField();
        cb_rememberme = new javax.swing.JCheckBox();
        pa_signup = new javax.swing.JPanel();
        lb_beforesignup = new javax.swing.JLabel();
        lb_signup = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library System");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pa_top.setBackground(new java.awt.Color(0, 173, 181));
        pa_top.setToolTipText("");

        loginLabel.setFont(new java.awt.Font("Kanit", 0, 48)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("Account Login");

        javax.swing.GroupLayout pa_topLayout = new javax.swing.GroupLayout(pa_top);
        pa_top.setLayout(pa_topLayout);
        pa_topLayout.setHorizontalGroup(
            pa_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        pa_topLayout.setVerticalGroup(
            pa_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(pa_top, java.awt.BorderLayout.NORTH);

        pa_center.setBackground(new java.awt.Color(57, 62, 70));

        lb_username.setFont(new java.awt.Font("Kanit", 0, 24)); // NOI18N
        lb_username.setForeground(new java.awt.Color(255, 255, 255));
        lb_username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_username.setText("Username : ");

        lb_password.setFont(new java.awt.Font("Kanit", 0, 24)); // NOI18N
        lb_password.setForeground(new java.awt.Color(255, 255, 255));
        lb_password.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_password.setText("Password : ");

        btn_login.setBackground(new java.awt.Color(21, 101, 192));
        btn_login.setFont(new java.awt.Font("Kanit", 1, 24)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("Login");
        btn_login.setBorder(null);
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        tf_username.setFont(new java.awt.Font("Kanit", 0, 18)); // NOI18N

        cb_rememberme.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        cb_rememberme.setForeground(new java.awt.Color(255, 255, 255));
        cb_rememberme.setText("Remember me");
        cb_rememberme.setFocusPainted(false);

        pa_signup.setBackground(pa_center.getBackground());

        lb_beforesignup.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        lb_beforesignup.setForeground(new java.awt.Color(204, 204, 204));
        lb_beforesignup.setText("Don't have an account?");

        lb_signup.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        lb_signup.setForeground(new java.awt.Color(102, 153, 255));
        lb_signup.setText("Sign up here!");
        lb_signup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_signupMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pa_signupLayout = new javax.swing.GroupLayout(pa_signup);
        pa_signup.setLayout(pa_signupLayout);
        pa_signupLayout.setHorizontalGroup(
            pa_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pa_signupLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_beforesignup, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_signup)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pa_signupLayout.setVerticalGroup(
            pa_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lb_signup, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lb_beforesignup, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pa_centerLayout = new javax.swing.GroupLayout(pa_center);
        pa_center.setLayout(pa_centerLayout);
        pa_centerLayout.setHorizontalGroup(
            pa_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa_centerLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(pa_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pa_centerLayout.createSequentialGroup()
                        .addComponent(lb_username, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_username, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pa_centerLayout.createSequentialGroup()
                        .addComponent(lb_password, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pa_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_rememberme)
                            .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(75, Short.MAX_VALUE))
            .addComponent(pa_signup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pa_centerLayout.setVerticalGroup(
            pa_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa_centerLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pa_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_username)
                    .addComponent(lb_username))
                .addGap(29, 29, 29)
                .addGroup(pa_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(cb_rememberme)
                .addGap(18, 18, 18)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pa_signup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pa_center, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        String username = tf_username.getText().trim();
        String password = pf_password.getText().trim();
        if (username.equals("admin") && password.equals("123456")) {
            save_rememberme_handle();
            System.out.println("Welcome Admin");
            new AdminGUI();
            this.dispose();
        }else{
            try {
                Connection con1 = Connect.connectDB();
                String sql = "Select * From userinfo where user=? and pass=?";
                PreparedStatement pst = con1.prepareStatement(sql);
                pst.setString(1, tf_username.getText());
                pst.setString(2, pf_password.getText());
                ResultSet rs = pst.executeQuery();
                if (rs.next()) {
                    save_rememberme_handle();
                    System.out.println(rs.getInt("userid"));
                    new UserGUI(rs.getInt("userid"));
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid user...");
                    tf_username.setText("");
                    pf_password.setText("");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void lb_signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_signupMouseClicked
        new RegisterForm();
        this.dispose();
    }//GEN-LAST:event_lb_signupMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        save_rememberme_handle();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        get_rememberme_handle();
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JCheckBox cb_rememberme;
    private javax.swing.JLabel lb_beforesignup;
    private javax.swing.JLabel lb_password;
    private javax.swing.JLabel lb_signup;
    private javax.swing.JLabel lb_username;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel pa_center;
    private javax.swing.JPanel pa_signup;
    private javax.swing.JPanel pa_top;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
}
