/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import database.Book;
import database.Connect;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author IsilenceT
 */
public class UserBorrow extends javax.swing.JPanel {

    /**
     * Creates new form UserBorrow
     */
    public UserBorrow(int userid) {
        initComponents();
        
        setBorrowTable(userid);
    }

    public void setBorrowTable(int userid){
         try {
            Connection con = Connect.connectDB();
             String queryhistory = "SELECT bname, borrowdate, returndate FROM borrowhistory "
                     + "INNER JOIN bookinfo ON borrowhistory.callnumber = bookinfo.callnumber "
                     + "WHERE userid = " + userid + " AND returned = 0";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(queryhistory);
            DefaultTableModel model = (DefaultTableModel) JTable_presentborrow.getModel();
            Object[] row = new Object[3];
            while (rs.next()){
                row[0] = rs.getString("bname");
                row[1] = rs.getString("borrowdate");
                row[2] = rs.getString("returndate");
                model.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_title = new javax.swing.JLabel();
        JScrollPane_presentborrow = new javax.swing.JScrollPane();
        JTable_presentborrow = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 204, 204));

        lb_title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_title.setText("รายการหนังสือที่ยืมอยู่ปัจจุบัน");

        JTable_presentborrow.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        JTable_presentborrow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ชื่อหนังสือ", "วันที่ยืม", "วันที่คืน"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTable_presentborrow.setRowHeight(30);
        JScrollPane_presentborrow.setViewportView(JTable_presentborrow);
        if (JTable_presentborrow.getColumnModel().getColumnCount() > 0) {
            JTable_presentborrow.getColumnModel().getColumn(1).setPreferredWidth(150);
            JTable_presentborrow.getColumnModel().getColumn(1).setMaxWidth(150);
            JTable_presentborrow.getColumnModel().getColumn(2).setPreferredWidth(150);
            JTable_presentborrow.getColumnModel().getColumn(2).setMaxWidth(150);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lb_title, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(JScrollPane_presentborrow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lb_title, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JScrollPane_presentborrow, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane_presentborrow;
    private javax.swing.JTable JTable_presentborrow;
    private javax.swing.JLabel lb_title;
    // End of variables declaration//GEN-END:variables
}
